baseURL = "https://duffney.dev"
languageCode = "en-us"
title = "duffney.io"
theme= "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

# googleAnalytics = "UA-173628310-1"
# disqusShortname = "duffney"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "engineering focus in a distracted world"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

# Colors for favicons
[params.favicon.color]
  mask = "#252627"
  msapplication = "#252627"
  theme = "#252627"

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "duffney.io (dev)"
    subtitle = ""
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "_ duffney.io"
      logoHomeLink = "/"

[params.portrait]
  path = "/img/portrait.jpg"
  alt = "Portrait"

[permalinks]
  posts = "/:title"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/joshduffney"
  [[params.social]]
    name = "github"
    url  = "https://github.com/Duffney"
  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/joshduffney/"
  [[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/3934865/joshduffney"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "blog"
    url        = "/posts"

  [[menu.main]]
    identifier = "start here"
    name = "start here"
    url = "/start-here/"
    weight = -100

